### ISSUE TITLE
python -m pip issue

### ISSUE THREAD

**Issue by braytac** [caltechlibrary/handprint#15]
Dear Mike:
Thanks for such a great piece of software. I discovered it a few weeks ago, and I am using it to dump (tentatively, roughly) microfilms from familysearch.org to text, that have not yet been indexed (maybe never).
Thanks to the program of you can save months of turning the page trying to read old writing trying to find a last name.
I do not know if it corresponds, but I comment that the 1st time when trying to install, as the documentation indicates:

python3 -m pip install git+https@github.com:caltechlibrary/handprint.git --user --upgrade

I got the following error.
"ERROR: Invalid requirement: 'git+https@github.com:caltechlibrary/handprint.git'
Hint: It looks like a path. File 'git+https@github.com:caltechlibrary/handprint.git' does not exist."

In my case it does work:
python -m pip install -e git+https://github.com/caltechlibrary/handprint.git@master#egg=handprint  --user --upgrade

, with:
git version 2.25.1
Python 3.8.1
pip 19.3.1 

Again thank you very much!
Cheers!

**Comment by mhucka** [comment]
Thank you for reporting this. I checked it in my own environment, and sure enough, it fails to work with the same error. This is very puzzling because I've used basically the same installation instructions for a bunch of programs and others fail too. Maybe something changed in how GitHub handles git urls?  Anyway, I'll update the docs as soon as I can figure out what's wrong.

**Comment by mhucka** [comment]
The URL mentioned in the README is now a corrected version of the original. It's a little bit simpler than the one you ended up using. It works in my environment, but if it fails for you, please let me know so that I correct it (again).
